FROM node:20-alpine
WORKDIR /app
COPY backend/package.json backend/package-lock.json* ./
RUN npm install --production --legacy-peer-deps
COPY backend ./backend
WORKDIR /app/backend
EXPOSE 5000
CMD ["node", "src/server.js"]
